//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Illallangi.FlightLog")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("Flight Log")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2013")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("4560e272-e976-41a7-aee2-f7a04533c85d")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]